name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# env:  
#   CODECOV_TOKEN: ${{ secrets.IOS_UTILS_CODECOV_TOKEN }}     

jobs:
  ci:
    name: Testing random framework
    runs-on: [self-hosted, macOS, X64]    
    timeout-minutes: 12 
    
    steps:    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env: 
          ImageOS: macos1015
        with:
          ruby-version: 2.7
         
      - name: Update cocoapods
        run: |    
          gem install bundler
          bundle install           
          cd WhimRandomExample && bundle exec pod install --repo-update

      - name: Running tests
        run: |                    
          set -o pipefail && xcodebuild -workspace WhimRandomExample/WhimRandomExample.xcworkspace -scheme WhimRandomExample -derivedDataPath Build/ -enableCodeCoverage YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' build test | xcbeautify

      # Upload coverage to codecov when there is test
      # - name: Format coverage files with slather
      #   run: |
      #     bundle exec slather

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3.1.1
      #   with: 
      #     token: ${{ env.CODECOV_TOKEN }}
      #     directory: ./
